name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: |
        for file in */*.csproj; do
          echo "Restoring dependencies for $file"
          dotnet restore "$file"
        done
    - name: Build
      run: |
        for file in */*.csproj; do          
          echo "Build dependencies for $file"
          dotnet build "$file"
        done
    - name: Run tests
      run: dotnet test ViaCepLibrary.Tests/ViaCepLibrary.Tests.csproj --no-build --verbosity normal